source 'https://rubygems.org'

# Install omnibus and omnibus-software
gem 'omnibus', github: 'chef/omnibus', branch: 'main'
gem 'omnibus-software', github: 'chef/omnibus-software', branch: 'main'

# Use Test Kitchen with Vagrant for convering the build environment
# gem 'rsync'
gem 'rake'
